spring.banner.location=banner/banner.txt

comands.list=/comandi - Mostra la lista dei comandi ,/AlbaTramonto - Mostra alba e tramonto di oggi,/ListaVisibili - Mostra tutti gli oggetti attulmente visibili e la loro posizione,/Oggetti - Apre una tastiera da cui e' possbile accedere ai dati dei vari oggetti


telegram.bot.username=SolarBot
telegram.bot.token=814488899:xxx

# token test 875502005:AAH7wBx1hsmmTio04RI4EgX9ZrDnY9QOl8g
log.file.path=/home/yury/source/bot/SolarBot
