spring.banner.location=banner/banner.txt

comands.list=/comandi - Mostra la lista dei comandi ,/AlbaTramonto - Mostra alba e tramonto di oggi,/ListaVisibili - Mostra tutti gli oggetti attulmente visibili e la loro posizione,/Oggetti - Apre una tastiera da cui e' possbile accedere ai dati dei vari oggetti


telegram.bot.username=SolarBot
telegram.bot.token=814488899:AAE7n6sUnclziB26FMtuw8HOmy8EEVH0x0c